services:
  api:
    build: .
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: devops_impl_db
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:18
    container_name: "postgresql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops_impl_db
    ports:
     - "5432:5432"